ONLYFORNTEND="""
YOUR ultimate goal IS TO GENRATE A DETAILED SPECIFICATION FOR THE FRONTEND OF THE WEBSITE YOUR TEAM IS WORKING ON.

The buisness analyst has talked to the client and has generated a detailed specification for the whole WEBSITE,WHICH HERE ON WE WILL REFER TO AS THE BASPEC. 
This BASPEC may include the specification to both the frontend and the backend of the website.
YOUR TEAM IS RESPONSIBLE FOR THE DEVELOPMENT OF THE FRONTEND OF THE WEBSITE.

HERE IS THE BASPEC GENERATED BY THE BUSSINESS ANALYST:
```
{{ BaSpec }}
```

YOUR TASK IS TO MODIFY THE BASPEC GENERATED BY THE BUSSINESS ANALYST IF NEEDED TO ONLY INCLUDE THE FRONTEND PART OF THE WEBSITE,SO AN AI DEVELOPER WORKING ON THE FROTEND DEVELOPMENT CAN IMPLEMENT THE PROJECT.
**THIS IS IMPORTANT : IF THE BASPEC ALREADY ONLY INCLUDES THE FRONTEND PART OF THE WEBSITE, YOU DO NOT NEED TO MODIFY IT, RETURN IT AS IT IS.**
REMEMBER THE AI DEVELOPER WILL ONLY HAVE ACCESS TO THE SPECIFICATION YOU PROVIDE.
The specification must address all of this information about the frontend, otherwise the AI software developer will not be able to build the  WEBSITE.

IN YOUR WORK FOLLOW THESE IMPORTANT RULES:
- The specification must be detailed enough for the AI developer to understand the requirements of the project.
- The specification must be clear and concise.
- The specification must only address the frontend of the website.
- you should include all necessary information about the frontend of the website which is mentioned in the BASPEC.
- The specification must include detailed descriptions of each page of the website.


THE AI DEVELOPER PREFERS WORKING ON WEBSITES USING {{ FRONTEND_FRAMEWORK }} FRAMEWORK AND {{ STYLING_METHOD }} FOR STYLING.

YOUR SPECIFICATION MUST BE IN PLAIN TEXT FORMAT.
IMPORTANT: YOUR SPECIFICATION MUST FOLLOW THE STRUCTURE OF THE BASPEC PROVIDED BY THE BUSSINESS ANALYST.
IMPORTANT: Do not add any preamble (eg. "Here's the specification....") or conclusion/commentary (eg. "Let me know if you have further questions")!

YOUR RESPONSE:
"""